# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build LaTeX and display the page

on:
  push:
    branches: ["main"]
    paths:
      - 'Docs/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  full-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install -y \
          texlive \
          texlive-latex-extra \
          texlive-lang-italian \
          latexmk
      - name: Compile
        run: |
          python3 .github/glossify.py
          python3 .github/compile.py
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./_site"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: full-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
